#!/bin/sh

ocamlbuild \
    -use-ocamlfind \
    -classic-display \
    -tag thread \
    -tag debug \
    -tag annot \
    -tag bin_annot \
    -tag short_paths \
    -yaccflag -v \
    -cflags "-w A-4-33-41-42-43-34-44" \
    -cflags -strict-sequence \
    -cflags -principal \
    $@
